import './styles/style.scss'
import './favicon.ico'
import './components/registration-popup/_registration-popup'
import './components/sign-in-popup/_sign-in-popup'
import './components/subscription-popup/_subscription-popup'
import './components/header/_header'
import './components/footer/_footer'
import './components/index-page/_index-page'
import './components/find-numbers-form/_find-numbers-form'
import './components/calendar/_calendar'
import './components/dropdown/_dropdown'
import './components/dropdown-counter-guests/_dropdown-counter-guests'
import './components/dropdown-counter-facilities/_dropdown-counter-facilities'
import './components/price-range/_price-range'
import './components/additional-facilities-list/_additional-facilities-list'
import './components/room-item/_room-item'
import './components/rooms-list/_rooms-list'
import './components/room-rewiews-item/_room-rewiews-item'
import './components/room-information/_room-information'
import './components/room-impressions/_room-impressions'
import './components/filter-room/_filter-room'


